### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by BenjazEth** [umair-khanzada/role-based-access-control#12]
https://github.com/umair-khanzada/role-based-access-control/blob/792d90f228273a361522ab74142663226c10bfb0/src/utils/index.js#L16

Even If I have this array of children routes passed as parameter to getAllowedRoutes() function it kept telling me of Type Error.
here are my list of routes 
![Capture](https://user-images.githubusercontent.com/34559038/120085976-8212e780-c091-11eb-9afe-2f35fbf4ddce.PNG)

**Comment by ukhanzada-nisum-com** [comment]
@BenjazEth Could you please log the parameter and check what is the value of the parameter when the `getAllowedRoutes` call.
